### ISSUE TITLE
Create Relaton flavor for BIPM

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-bipm#1]
BibItem model here: https://github.com/metanorma/metanorma-model-bipm/blob/master/images/BipmBibliographicItem.png

Please change it if necessary. Thanks!

**Comment by ronaldtse** [comment]
Acronyms for BIPM committees:

CCAUV Comité consultatif de l’acoustique, des ultrasons et des vibrations/ Consultative Committee for Acoustics, Ultrasound and Vibration
CCDS Comité consultatif pour la définition de la seconde/
Consultative Committee for the Definition of the Second, see CCTF
CCE Comité consultatif d’électricité/
Consultative Committee for Electricity, see CCEM
CCEM (formerly the CCE) Comité consultatif d’électricité et magnétisme/ Consultative Committee for Electricity and Magnetism
CCL Comité consultatif des longueurs/Consultative Committee for Length
CCM Comité consultatif pour la masse et les grandeurs apparentées/
Consultative Committee for Mass and Related Quantities
CCPR Comité consultatif de photométrie et radiométrie/
Consultative Committee for Photometry and Radiometry
CCQM Comité consultatif pour la quantité de matière : métrologie en chimie et
biologie/Consultative Committee for Amount of Substance: Metrology in
Chemistry and Biology
CCRI Comité consultatif des rayonnements ionisants/
Consultative Committee for Ionizing Radiation CCT Comité consultatif de thermométrie/
Consultative Committee for Thermometry
CCTF (formerly the CCDS) Comité consultatif du temps et des fréquences/
Consultative Committee for Time and Frequency
CCU Comité consultatif des unités/Consultative Committee for Units CGPM Conférence générale des poids et mesures/
General Conference on Weights and Measures CIPM Comité international des poids et mesures/
International Committee for Weights and Measures

**Comment by opoudjis** [comment]
Both the name and the acronym must be included in the record, as `<committee acronym="ACRONYM">NAME</committee>`. Updating grammar now.

**Comment by ronaldtse** [comment]
@andrew2net is this completed? If so please help close it. Thanks.

**Comment by andrew2net** [comment]
> BibItem model here: https://github.com/metanorma/metanorma-model-bipm/blob/master/images/BipmBibliographicItem.png

@ronaldtse the model doesn't match the grammar https://github.com/metanorma/metanorma-model-iso/blob/master/grammars/bipm.rnc
We test generated XML files against the grammar. Which model is correct?

**Comment by ronaldtse** [comment]
Ping @opoudjis what’s the answer?

**Comment by andrew2net** [comment]
@ronald I've updated the model according to the latest grammar. Can we close the issue?

**Comment by opoudjis** [comment]
Yes. The model was done first, and the grammar is always closer to the code.
