### ISSUE TITLE
Fetch of BIPM PV 105 is not working

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-bipm#14]
... and used to

**Comment by andrew2net** [comment]
@opoudjis now the correct reference is `BIPM CIPM Decision 105`

**Comment by manuel489** [comment]
> OK, will change my test file. Will also need to get editors to update BIPM brochure, if they haven't already.

I believe we haven't :). Have assigned myself as a remainder.

**Comment by andrew2net** [comment]
@opoudjis what else do we need to do here? Update BIPM brochure?

**Comment by manuel489** [comment]
@andrew2net there is a doubt about the rendering of fetched BIPM references exposed in https://github.com/metanorma/bipm-si-brochure/issues/145#issuecomment-1114072781

**Comment by ronaldtse** [comment]
@manuel489 the rendering of a reference is done in Metanorma, so we would need to ask @opoudjis

**Comment by ronaldtse** [comment]
@manuel489 is the default rendering in Metanorma not correct? I think we need to ask @opoudjis about relaton-render.

**Comment by manuel489** [comment]
Question [answered](https://github.com/metanorma/bipm-si-brochure/issues/145#issuecomment-1118534365).
From my understanding, there is nothing else to do here.
I think we can close this ticket.
