### ISSUE TITLE
Update CGPM identifiers

### ISSUE THREAD

**Issue by andrew2net** [relaton/relaton-bipm#15]
1. we need to remove BIPM from identifiers
2. since the numbers restart each year, therefore we need the CGPM document identifier to be year-id, where the id number is 0 if there is only one CGPM document for that year

**Comment by andrew2net** [comment]
@ronaldtse @opoudjis in CGPM meetings we create documents from [metadata](https://github.com/metanorma/bipm-data-outcomes/blob/d625c7216260970de3904e4979c12f0b34679e3c/cgpm/meetings-en/meeting-09.yml#L2-L7) and [resolutions](https://github.com/metanorma/bipm-data-outcomes/blob/d625c7216260970de3904e4979c12f0b34679e3c/cgpm/meetings-en/meeting-09.yml#L8)
So in the examples, we create a document from the metadata with id `CGMP Resolution 1948` or `CGMP Resolution 1948-09`?
From the resolutions, we create `CGMP Resolution 1948-nn`. Right? In case we create `CGMP Resolution 1948-09` from the metadata we will have collision because there is a [resolution 9](https://github.com/metanorma/bipm-data-outcomes/blob/d625c7216260970de3904e4979c12f0b34679e3c/cgpm/meetings-en/meeting-09.yml#L273-L294)

**Comment by ronaldtse** [comment]
@andrew2net there is a misunderstanding here. (also, "CGPM", not "CGMP")

1. 
This file is the data for "CGPM Meeting 9", as described in the title:
https://github.com/metanorma/bipm-data-outcomes/blob/d625c7216260970de3904e4979c12f0b34679e3c/cgpm/meetings-en/meeting-09.yml#L3
"9th meeting of the CGPM"

2. 
https://github.com/metanorma/bipm-data-outcomes/blob/d625c7216260970de3904e4979c12f0b34679e3c/cgpm/meetings-en/meeting-09.yml#L273-L294

This is the data for "Resolution 9 of CGPM Meeting 9", i.e. "CGPM Resolution 9 (1948)".

**Comment by andrew2net** [comment]
> This is the data for "Resolution 9 of CGPM Meeting 9", i.e. "CGPM Resolution 9 (1948)".

@ronaldtse so the reference should be `BIPM CGPN Resolution 1948-09` but the identifier `CGPM Resolution 9 (1948). Is it correct?

**Comment by ronaldtse** [comment]
@andrew2net Yes. (but instead of "BIPM CGPM Resolution 1948-09", why not just "CGPM Resolution 1948-09"?)

Can we also accept "CGPM Resolution 9 (1948)" as the search reference too?
