### ISSUE TITLE
Incorrect semantic structure in CIPM/CGPM reference identifiers

### ISSUE THREAD

**Issue by manuel489** [relaton/relaton-bipm#17]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/145*

Identifiers like `CIPM Resolution 41` fetch this text:
 "CIPM Resolution 41 Bureau International des Poids et Mesures. *41e réunion du CIPM (1945, 1946)*. 1946."

However, the number "41" corresponds to the *Meeting*, not the Resolution.
Like shown in: https://www.bipm.org/en/committees/ci/cipm/41-1946,
the report of this Meeting contains two resolutions.

Currently, BIPM Brochure contains a bunch of references that have this structure:

````
[bibliography]
== Bibliography
...
* [[[PV20,CIPM Resolution 41]]]
* [[[PV21,CIPM Resolution 42]]]
* [[[PV22,CIPM Resolution 43]]]
* [[[PV25,CIPM Resolution 46]]]
* [[[PV29,CIPM Resolution 50]]]
* [[[PV30,CIPM Resolution 51]]]
* [[[PV32,CIPM Resolution 53]]]
* [[[PV35,CIPM Resolution 56]]]
...
````

In my opinion, this is wrong and confusing.

**Comment by ronaldtse** [comment]
Related to https://github.com/metanorma/metanorma-bipm/issues/164

**Comment by manuel489** [comment]
Thanks @ronaldtse!
