### ISSUE TITLE
Some CIPM references are not fetching

### ISSUE THREAD

**Issue by manuel489** [relaton/relaton-bipm#18]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/145*

Following identifiers are not fetching:
````
CIPM Resolution 43
CIPM Resolution 51
CIPM Resolution 59
CIPM Resolution 62
````

Like I've stated in this thread: https://github.com/relaton/relaton-bipm/issues/17
Numbers correspond to the *Meeting*, not the Resolution.

The correspondence with original document is as follows:
CIPM Resolution 43 -> (PV, **22**, 92)
CIPM Resolution 51 -> (PV, **30**, 27)
CIPM Resolution 59 -> (PV, **38**, 110-111)
CIPM Resolution 62 -> (PV, **1879**, 41)

For `CIPM Resolution 59` there is data available in the web: https://www.bipm.org/en/committees/ci/cipm/59-1970,
so the fetching should occur in this case. I can't say the same for the others, however.

**Comment by ronaldtse** [comment]
> Numbers correspond to the Meeting, not the Resolution.

What do you mean? Do you want to cite using the Meeting number, or the Resolution number?

**Comment by ronaldtse** [comment]
The **correct format** is specified here: https://github.com/metanorma/metanorma-bipm/issues/164

> From Janet Miles of the BIPM:
> 
> For the Resolutions/Recommendations/Decisions I think the following simple rule works without any ambiguity:
> 
> English:
> ```
> [BODY] [Type] {number} (YEAR)
> ```
>  
> (where the number can be omitted if necessary, and the Type will be Resolution/Recommendation/Declaration as appropriate).
> 
> French (in French an additional dash is required as follows):
> ```
> [BODY] - [Type] {number} (YEAR)
> ```
> (and of course the Type has to be specified in French : Résolution,  Recommandation, Déclaration…)
> 
> Examples:
> ```
> CGPM Resolution 6 (1987)
> CIPM Resolution (1948)
> CCDS Recommendation 2 (1970)
> ```

We are no longer using these:
> The correspondence with original document is as follows:
> CIPM Resolution 43 -> (PV, 22, 92)
> CIPM Resolution 51 -> (PV, 30, 27)
> CIPM Resolution 59 -> (PV, 38, 110-111)
> CIPM Resolution 62 -> (PV, 1879, 41)
