### ISSUE TITLE
(URGNET) Identifier to retrieve CCDS Recommendation 2 (1970)

### ISSUE THREAD

**Issue by manuel489** [relaton/relaton-bipm#20]
We need to reference this page: https://www.bipm.org/en/committees/cc/cctf/5-1970/resolution-2.
What would be the correct identifier to retrieve data from [1970-02.yaml](https://github.com/relaton/relaton-data-bipm/blob/master/data/cctf/recommendation/1970-02.yaml)?

**Comment by manuel489** [comment]
We also need to refer to this page: https://www.bipm.org/en/committees/ci/cipm/50-1961/resolution-

**Comment by ronaldtse** [comment]
@manuel489 the proper identifier is "CCDS Resolution 1970-05" or "CCTF Resolution 1970-05". Does this not work?

> We also need to refer to this page: https://www.bipm.org/en/committees/ci/cipm/50-1961/resolution-

The data source of this resolution is available at https://github.com/metanorma/bipm-data-outcomes/blob/main/cipm/meetings-en/meeting-50.yml

**Comment by manuel489** [comment]
> the proper identifier is "CCDS Resolution 1970-05" or "CCTF Resolution 1970-05". Does this not work?

**Comment by manuel489** [comment]
I've also used `CCDS Recommendation 02 (1970)` as identifier. Which should be the proper way?

**Comment by ronaldtse** [comment]
> Curiously, the identifiers are being related to CALCONNECT instead of BIPM.

That is wrong. @andrew2net can you please help here?

**Comment by andrew2net** [comment]
> Curiously, the identifiers are being related to CALCONNECT instead of BIPM.

it's fixed in the relaton-bipm 1.11.7 and relaton 1.11.3

> the proper identifier is "CCDS Resolution 1970-05" or "CCTF Resolution 1970-05". Does this not work?

We don't have CCDS body in bipm-data-outcomes. For CCTF body there are "CCTF Recommendation 1970-02" and "CCTF Meetings 5" document.

**Comment by manuel489** [comment]
> We don't have CCDS body in bipm-data-outcomes. For CCTF body there are "CCTF Recommendation 1970-02" and "CCTF Meetings 5" document.

@andrew2net *CCDS* is the same as *CCTF*. It's just an old body name that was used before CCTF.
So this identifier: "CCDS Recommendation 1970-02", should be equivalent to "CCTF Recommendation 1970-02".

**Comment by manuel489** [comment]
For more information, please check point 2 from this thread: https://github.com/metanorma/metanorma-bipm/issues/164

**Comment by andrew2net** [comment]
@manuel489 can we close this issue?

**Comment by andrew2net** [comment]
> And one last question, what would be the proper identifier to fetch
> from this file: https://github.com/metanorma/bipm-data-outcomes/blob/main/cipm/meetings-en/meeting-50.yml
> (Note that this is a Meeting, not a specific resolution.)

@ronaldtse `CIPM Meetings 50`

**Comment by manuel489** [comment]
Confirmed, thanks!
