### ISSUE TITLE
(URGNET) Relaton BIPM files lack direct reference to data source (bipm-data-outcomes)

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-bipm#21]
A file like https://github.com/relaton/relaton-data-bipm/blob/master/data/cctf/recommendation/1970-02.yaml has no reference to the original machine-readable data source, which is https://github.com/metanorma/bipm-data-outcomes.

Every file should have a reference to the data source to allow further processing.

**Comment by andrew2net** [comment]
@ronaldtse in the bipm-data-outcomes there are two files for each document, English and French versions.
1. Should we add link to each translation?
2. What what type the links should be? `src-en` and `src-fr`?

**Comment by ronaldtse** [comment]
> Should we add link to each translation?

Probably.

> What type the links should be? src-en and src-fr?

Under `src` key, there can be `en` and `fr`.
