### ISSUE TITLE
(URGENT) Inconsistent file naming and resolution naming

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-bipm#22]
In relaton-data-bipm/data/cgpm/resolution , some files are not named correctly to the pattern `yyyy-ii` where yyyy is year and ii is the identifier.

e.g.
* https://github.com/relaton/relaton-data-bipm/blob/master/data/cgpm/resolution/21.yaml (This is actually 1999-21)
* https://github.com/relaton/relaton-data-bipm/blob/master/data/cgpm/resolution/3.yaml (This is actually the 1901 meeting, but there are resolution 1 and resolution 2.) The data source https://github.com/metanorma/bipm-data-outcomes/blob/main/cgpm/meetings-en/meeting-03.yml is correct.

As we can see from the second issue, this is purely a data parsing issue in Relaton-BIPM.

@andrew2net can you please help fix this ASAP? Thanks.

**Comment by andrew2net** [comment]
> * https://github.com/relaton/relaton-data-bipm/blob/master/data/cgpm/resolution/21.yaml (This is actually 1999-21)
> * https://github.com/relaton/relaton-data-bipm/blob/master/data/cgpm/resolution/3.yaml (This is actually the 1901 meeting, but there are resolution 1 and resolution 2.)

@ronaldtse
1. FYI:
the `cgpm/resolution/21.yaml` now is [cgpm/meetings/21.yaml](https://github.com/relaton/relaton-data-bipm/blob/master/data/cgpm/meetings/21.yaml)
the `cgpm/resolution/3.yaml ` now is [cgpm/meetings/3.yaml](https://github.com/relaton/relaton-data-bipm/blob/master/data/cgpm/meetings/3.yaml)

2. I didn't get why `21.yaml` should be named using pattern `yyyy-ii` but `3.yaml` using pattern `yyyy`?
3. References for these documents are `CGPM Meetings 21` and `CGPM Meetings 3`. Should the references be `CGPM Meetings 1999-21` and `CGPM Meetings 1901`?

**Comment by andrew2net** [comment]
> Resolutions (syntax 2):
> 
> * "CGPM Resolution 21-01" ([resolution 1 of meeting in 1999 which is Meeting 21](https://github.com/metanorma/bipm-data-outcomes/blob/59a48683f130986f3834d0a10c54e6ff9da20789/cgpm/meetings-en/meeting-21.yml#L10))
> * "CGPM Resolution 3-01" ([resolution 1 of meeting in 1903 which is Meeting 3](https://github.com/metanorma/bipm-data-outcomes/blob/59a48683f130986f3834d0a10c54e6ff9da20789/cgpm/meetings-en/meeting-03.yml#L10))

@ronaldtse do we really need the syntax 2? We have to create duplicated files with names matched to the syntax or create mapping file.

**Comment by ronaldtse** [comment]
Why not use an index? We should really not tie the file name pattern with the software.

**Comment by andrew2net** [comment]
@ronaldtse using index slows down fetching documents because it needs two HTTP request for each document. Maybe we need to consider caching indexes. I suggest to use singleton to keep index in memory. What do you think?

**Comment by ronaldtse** [comment]
@andrew2net I think having index on disk (cached) is a reasonable compromise.

**Comment by andrew2net** [comment]
@ronaldtse we can detect if a gem is run in Lambda then use S3 else use local fs.

**Comment by andrew2net** [comment]
> Resolutions (syntax 2):
> 
> * "CGPM Resolution 21-01" ([resolution 1 of meeting in 1999 which is Meeting 21](https://github.com/metanorma/bipm-data-outcomes/blob/59a48683f130986f3834d0a10c54e6ff9da20789/cgpm/meetings-en/meeting-21.yml#L10))
> * "CGPM Resolution 3-01" ([resolution 1 of meeting in 1903 which is Meeting 3](https://github.com/metanorma/bipm-data-outcomes/blob/59a48683f130986f3834d0a10c54e6ff9da20789/cgpm/meetings-en/meeting-03.yml#L10))

@ronaldtse some meetings have parts. For example [`CIPM Meeting 101-1`](https://github.com/relaton/relaton-data-bipm/blob/master/data/cipm/meeting/101-1.yaml). Should the syntax 2 looks like `CIPM Decision 101-1-01` or just `CIPM Decision 101-01`? The parts have end-to-end numbering, so the second version will produce unique references.

**Comment by ronaldtse** [comment]
Good find. I think the resolutions should be cited as "CIPM Meeting 101-01". The sub-meetings should not be used in resolutions/decision/etc numbering.

Can you help document these decisions in the README? Thanks.

**Comment by andrew2net** [comment]
@ronaldtse I think we need to add to the index `guide-ccl-gd-mep-1` and `si-brochure`. I noticed there are new documents in the `bipm-si-brochure` dataset. 
1. Do we need to convert all the documents from the dataset `documents` folder?
2. Some of the documents have English and French files. Do we need to compose them into one Relaton item?

**Comment by ronaldtse** [comment]
@andrew2net yes indeed. We need to add the index from those documents. But let's do that in a new issue?

> 1. Do we need to convert all the documents from the dataset's `site/documents` folder?

Yes.

> 2. Some of the documents have English and French files. Do we need to compose them into one Relaton item?

Yes.

> 3. What are the `*.presentation.xml` files in the `site/documents` folder?

Those documents are the Metanorma Presentation XML files. But those are not supposed to be in Git `main`? They are only supposed to be in `gh-pages` branch.

> 4. The `site/documents/sib-a4-en.xml` have a document identifier `BIPM `. Shouldn't it be something like `BIPM SIB-A4`?

I will have to check and get back to you...
