### ISSUE TITLE
(URGENT) Support new “declaration” type

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-bipm#23]
As implemented in https://github.com/metanorma/bipm-data-outcomes/pull/8 , relaton-bipm needs to support the “declaration” type of resolution. 

The syntax to refer to it would be “BODY Declaration (YYYY)” where BODY is the “subject”, YYYY is the “identifier”. 

In French it would be “BODY Déclaration YYYY”.

**Comment by andrew2net** [comment]
> In French it would be “BODY Déclaration YYYY”

@ronaldtse the Relaton model contains English and French translations in one item. Do we really need to have references in different languages?

**Comment by ronaldtse** [comment]
@andrew2net we should be able to fetch the same reference (which is bilingual) using English or French.

i.e. the data is bilingual. The fetch syntax (whether in English or French) retrieves the same item.
