### ISSUE TITLE
Some CIPM references stop rendering on second compilation

### ISSUE THREAD

**Issue by manuel489** [relaton/relaton-bipm#26]
I'm not sure if this issue is related to relaton-bipm.
Identifiers like `CIPM Resolution 3 (1956)` and `CIPM Recommendation (1961)`
stop rendering properly after executing a sencond compilation.

Output example:
![capture1](https://user-images.githubusercontent.com/33627611/171985871-3e377912-ab31-4494-918d-edb97c2d99f8.PNG)

They did render well on the first time when the fetching was performed.
But it seems that they are not being properly retrieved from the caching system.

I have to apply `:no-isobib-cache:` attribute to reset the fetching
and they render as expected again.

**Comment by manuel489** [comment]
@anermina, can you confirm this, please?

**Comment by ronaldtse** [comment]
This is possible when using a stale cache -- the relaton-data-bipm git repository has changed structure several times recently. Maybe that's why? Next time you can try directly deleting the `relaton/` directory in the document, and it will re-fetch the caches.

**Comment by anermina** [comment]
> This is possible when using a stale cache -- the relaton-data-bipm git repository has changed structure several times recently. Maybe that's why? Next time you can try directly deleting the `relaton/` directory in the document, and it will re-fetch the caches.

It seems to me this solves the issue.

**Comment by andrew2net** [comment]
> Identifiers like `CIPM Resolution 3 (1956)` and `CIPM Recommendation (1961)`
> stop rendering properly after executing a sencond compilation.

The reference `CIPM Resolution 3 (1956)` is `CIPM Recommendation 3 (1956)` now.
I've rendered the references `CIPM Recommendation 3 (1956)` and `CIPM Recommendation (1961)` many times without any problems.

**Comment by manuel489** [comment]
> This is possible when using a stale cache -- the relaton-data-bipm git repository has changed structure several times recently. Maybe that's why? Next time you can try directly deleting the relaton/ directory in the document, and it will re-fetch the caches.

Thanks @ronaldtse, you're right. This is the reason.
Closing.
