### ISSUE TITLE
Support CGPM Proceedings

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-bipm#3]
https://www.bipm.org/en/worldwide-metrology/cgpm/comptes-rendus.html

**Comment by ronaldtse** [comment]
Rendered like this:

![](https://user-images.githubusercontent.com/11865/125016185-7ad4f580-e0a3-11eb-8c14-520764f48bc8.png)

**Comment by andrew2net** [comment]
@ronaldtse the link above doesn't work

<img width="582" alt="image" src="https://user-images.githubusercontent.com/5623890/125600227-af475f2c-b4d5-435c-9383-1595a51502b8.png">

**Comment by ronaldtse** [comment]
We can use these:
* https://www.bipm.org/en/committees/cg/cgpm/publications
* https://github.com/metanorma/cgpm-resolutions

**Comment by andrew2net** [comment]
@ronaldtse as I remember we have converted these documents from https://github.com/metanorma/cgpm-resolutions to https://github.com/relaton/relaton-data-bipm
Do we need to make the relaton-bipm fetch these documents from the relaton-data-bipm repo?

**Comment by opoudjis** [comment]
https://github.com/metanorma/bipm-data-outcomes/tree/main/cipm

**Comment by andrew2net** [comment]
fixed in https://github.com/relaton/relaton-data-bipm/commit/f9bacecbc4269a9bcb3a508551c023b9c1c4f12a and https://github.com/relaton/relaton-bipm/commit/689471576dd89326332239e8d9ace00709e54770

**Comment by opoudjis** [comment]
There are missing volumes, but they do not seem to be cited in the BIPM brochure—as far as I can tell, because they made no resolutions. I'd rather we still rendered something for a missing volume, but it doesn't particularly matter. Closing this ticket.
