### ISSUE TITLE
Corporate author of proceedings

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-bipm#33]
I've asked CGPM/CIPM/CCTF to be made proceedings. Proceedings need an author or editor. As requested by Ronald in https://github.com/metanorma/metanorma-iso/issues/776 , please make CGPM/CIPM/CCTF the authors of all matching works.

**Comment by ronaldtse** [comment]
This ticket as well: https://github.com/relaton/relaton-data-bipm/issues/22

**Comment by andrew2net** [comment]
fixed https://github.com/relaton/relaton-data-bipm/issues/22#issuecomment-1257167931
