### ISSUE TITLE
Document IOP Anti-DDOS detection in the README

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-bipm#36]
@andrew2net can you also document the Anti-DDOS detection in the README? And how the user can address it. Thanks.

_Originally posted by @ronaldtse in https://github.com/relaton/relaton-data-bipm/issues/23#issuecomment-1251752061_

**Comment by andrew2net** [comment]
Added the doc here https://github.com/relaton/relaton-bipm#search-for-a-standard-using-keywords

**Comment by ronaldtse** [comment]
Thanks!
