### ISSUE TITLE
Faulty titles in BIPM Metrologia references

### ISSUE THREAD

**Issue by anermina** [relaton/relaton-bipm#37]
Fetched titles of several BIPM Metrologia references include `less` and `greater` parameters.

````
bundle exec relaton fetch "BIPM Metrologia 55 1 L13"

<bibdata type="article">
  <fetched>2022-09-19</fetched>
  <title type="title-main" format="text/plain" language="en" script="Latn">The {CODATA} 2017 values of$\less$i$\greater$h$\less$/i$\greater$,$\less$i$\greater$e$\less$/i$\greater$,$\less$i$\greater$k$\less$/i$\greater$, and$\less$i$\greater$N$\less$/i$\greater$$\less$sub$\greater$A$\less$/sub$\greater$for the revision of the {SI}</title>
  <title type="main" format="text/plain" language="en" script="Latn">The {CODATA} 2017 values of$\less$i$\greater$h$\less$/i$\greater$,$\less$i$\greater$e$\less$/i$\greater$,$\less$i$\greater$k$\less$/i$\greater$, and$\less$i$\greater$N$\less$/i$\greater$$\less$sub$\greater$A$\less$/sub$\greater$for the revision of the {SI}</title>
  <uri type="src">https://iopscience.iop.org/article/10.1088/1681-7575/aa950a</uri>
  <uri type="doi">https://doi.org/10.1088/1681-7575/aa950a</uri>
````

Therefore, we don't get the correct rendering of those references:
![image](https://user-images.githubusercontent.com/55683568/191349924-e0e7da35-9c76-4b62-9f08-5f54bff5ac0e.png)

**Comment by andrew2net** [comment]
@ronaldtse title has a format option. We can use `text/html` format and have title with HTML content.

**Comment by andrew2net** [comment]
fixed in relaton-bib v1.13.8 and relaton-bipm v1.13.8

**Comment by opoudjis** [comment]
Of course, Metanorma expects content to be marked up in Metanorma, @andrew2net if there a Metanorma option on the titles? If not, I'll need to implement an HTML to Metanorma translator my side.

**Comment by ronaldtse** [comment]
I do not think HTML is a solution. This is LaTeX math in the title.

**Comment by ronaldtse** [comment]
> If not, I'll need to implement an HTML to Metanorma translator my side.

That's a huge stretch. I'm not sure we really want that.

**Comment by andrew2net** [comment]
> Of course, Metanorma expects content to be marked up in Metanorma, @andrew2net if there a Metanorma option on the titles? If not, I'll need to implement an HTML to Metanorma translator my side.

@opoudjis title is a subclass of [FormattedString](https://github.com/relaton/relaton-models/blob/0d06e95fb2eabfa30d95d274f4055e7b7cb3c943/grammars/biblio.rnc#L71) and it allows "text/html" format. We don't need full HTML support, just some markup that we already have in abstract (abstract is also FormattedString).

> I do not think HTML is a solution. This is LaTeX math in the title.

@ronaldtse it's not a math, it's just italic and subscript markup:
```xml
<title type="title-main" format="text/html" language="en" script="Latn">The CODATA 2017 values of <i>h</i>, <i>e</i>, <i>k</i>, and <i>N</i><sub>A</sub> for the revision of the SI</title>
```

<img width="687" alt="image" src="https://user-images.githubusercontent.com/5623890/191711677-56a4bca1-d03a-4260-b0fd-b44cfe54ab2a.png">

**Comment by opoudjis** [comment]
> @opoudjis title is a subclass of [FormattedString](https://github.com/relaton/relaton-models/blob/0d06e95fb2eabfa30d95d274f4055e7b7cb3c943/grammars/biblio.rnc#L71) and it allows "text/html" format. We don't need full HTML support, just some markup that we already have in abstract (abstract is also FormattedString)

Yes, I know that. But *I*'m consuming these bibitems, and I'm consuming them in the context of Metanorma. So I'm asking you, whether a Metanorma XML option is available...

>  just some markup that we already have in abstract (abstract is also FormattedString).

Yes, and when this came up in IETF, we got away with it because p is shared between Metanorma XML and HTML; in fact, a lot of markup is.

On the other hand, `<i>` and `<b>` are not: Metanorma only understands `<strong>` and `<em>`.

So we still have a problem:

* Either I write an HTML to Metanorma XML translator to consume these strings,
* Or you add a Metaorma XML string
* Or we agree on a limited number of tags shared by Metanorma XML and HTML

**Comment by andrew2net** [comment]
Fixed.
```xml
<title type="title-main" format="text/html" language="en" script="Latn">The CODATA 2017 values of <em>h</em>, <em>e</em>, <em>k</em>, and <em>N</em><sub>A</sub> for the revision of the SI</title>
```

**Comment by opoudjis** [comment]
So, we have for now gone for a solution of only using tags shared between Metanorma and HTML. Eventually, this will break, when we start using MathML in titles, and I will implement a translator.
