### ISSUE TITLE
Normalize non-ASCII characters into Unicode characters

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-bipm#40]
https://github.com/metanorma/bipm-si-brochure/issues/203

`<completename language="en" script="Latn">de Mirand{\'{e}}s, Estefan{\'{\i}}a</completename>`

That is LaTeX, and of course, I'm not expecting LaTeX. Very very very very strongly request that such characters be resolved into the correct UTF-8 characters; we can safely assume in 2022 that consumers can process UTF-8.

**Comment by opoudjis** [comment]
From @ronaldtse 

> This issue requires Relaton to deal with BibTeX parsing and semantics. As you remember the {...} means that capitalization should not be changed for the text in between. We've never dealt with those and will need to.

> In any case, this issue is not part of the SI Brochure, this is for the MEPs, so should not be affected by the milestone.

**Comment by ronaldtse** [comment]
This is the BibTeX syntax that we need to parse and we will need some library to do a reasonable job of normalizing them.

**Comment by andrew2net** [comment]
@opoudjis it seems the issue doesn't exist in the last relaton-bipm version 1.14.1.
```
relaton fetch "BIPM Metrologia 55 1 L13"
[relaton-bipm] ("BIPM Metrologia 55 1 L13") fetching...
[relaton-bipm] ("BIPM Metrologia 55 1 L13") found Metrologia 55 1 
<bibdata type="article" schema-version="v1.2.1">
...
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <completename language="en" script="Latn">E de Mirandés</completename>
      </name>
    </person>
  </contributor>
```
Could you check it please?

**Comment by opoudjis** [comment]
Confirmed, closing
