### ISSUE TITLE
Missing Metrologia final page numbers

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-bipm#42]
This appears to be a data quality issue. 

Metrologia articles are now being cited only with their initial page, not with the range of pages they have. (I cannot believe that Metrologia only publishes one-page–long articles.)

So

`bundle exec relaton fetch "BIPM Metrologia 34 3 261"`

returns

````
  <extent>
    <locality type="page">
      <referenceFrom>261</referenceFrom>
    </locality>
  </extent>
````

In https://github.com/metanorma/metanorma-iso/issues/775, it was rendering with pp 261-290.

The problem is that the Bibtex reference and online rendering at https://iopscience.iop.org/article/10.1088/0026-1394/34/3/9/meta

Also give only the starting page.

That's bad quality data, but I believe we should be correcting it. How did we establish the end of the page number range before?

**Comment by ronaldtse** [comment]
For this particular entry:
https://github.com/relaton/rawdata-bipm-metrologia/blob/main/2022-04-05T10_55_52_content/0026-1394/0026-1394_34/0026-1394_34_3/0026-1394_34_3_261/me7309.xml

It does provide the page numbers.
```xml
      <fpage>261</fpage>
      <lpage>290</lpage>
```

However, not all Metrologia entries provide page numbers:
* https://github.com/relaton/rawdata-bipm-metrologia/blob/main/2022-06-02T03_01_55_content/0026-1394/0026-1394_59/0026-1394_59_4/0026-1394_59_4_045001/met_59_4_045001.xml

This one has no page (first or last) number.

**Comment by andrew2net** [comment]
> However, not all Metrologia entries provide page numbers:
> 
> * https://github.com/relaton/rawdata-bipm-metrologia/blob/main/2022-06-02T03_01_55_content/0026-1394/0026-1394_59/0026-1394_59_4/0026-1394_59_4_045001/met_59_4_045001.xml
> 
> This one has no page (first or last) number.

@ronaldtse what does the `<page-count count="9"/>` element mean? Does it happen to mean pages from 1 to 9?

**Comment by ronaldtse** [comment]
Maybe, it might mean it is a book of 9 pages, so 1-9. Let’s just assume that for now. Can you find this item online?

**Comment by andrew2net** [comment]
@ronaldtse found it [here](https://iopscience.iop.org/article/10.1088/1681-7575/ac635c) but don't see any pages.

**Comment by ronaldtse** [comment]
@andrew2net in that link the original PDF looks like this:
<img width="1156" alt="Screenshot 2023-02-11 at 8 55 10 AM" src="https://user-images.githubusercontent.com/11865/218228370-3bffe46e-ad9e-4d14-b49d-0335773a2a1b.png">

There is really no page number. It seems that in this Metrologia number they really do not use page numbers anymore. Each article is individually marked with a number like 045001, 045002... 

<img width="412" alt="Screenshot 2023-02-11 at 8 56 33 AM" src="https://user-images.githubusercontent.com/11865/218228436-94d92f3f-93d7-4df5-bc2d-3fe85ef5398a.png">

So let's not insist on a page number, but use the article identifying number.

**Comment by andrew2net** [comment]
@opoudjis fixed in relaton-bipm v1.14.2, but it's discovered that IDs with a page number at the end are not unique, and some documents don't have a page number at all.
BIPM uses article numbers so we switched to using them too.
May be should find another way to avoid duplication of IDs because some article numbers look weird. For example `ac1e04`.
So the "BIPM Metrologia 34 3 261" should be fetched with BIPM Metrologia 34 3 9" reference now.

**Comment by opoudjis** [comment]
Big change, and need to alert editors about this....

@anermina @manuelfuenmayor

**Comment by ronaldtse** [comment]
We actually need to separate the identification of "article number" and "first page" in the syntax. 3 consecutive numbers after "Metrologia" does not make sense.

**Comment by andrew2net** [comment]
fixed https://github.com/relaton/relaton-data-bipm/blob/436f9a9db429cfdb43975a580ed1c0990653d9d9/data/metrologia-34-3-9.yaml#L78-L79
