### ISSUE TITLE
(URGENT) Unable to fetch some BIPM items

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-bipm#46]
This is from the bipm-si-brochure:

```
[relaton] (CIPM Decision 2017-10) not found.
[relaton] (BIPM Metrologia 4 1 41) not found.
[relaton] (BIPM Metrologia 7 1 43) not found.
[relaton] (BIPM Metrologia 11 4 179) not found.
[relaton] (BIPM Metrologia 17 2 69) not found.
[relaton] (BIPM Metrologia 21 2 89) not found.
[relaton] (BIPM Metrologia 6 2 65) not found.
[relaton] (BIPM Metrologia 8 1 32) not found.
[relaton] (BIPM Metrologia 16 1 55) not found.
[relaton] (BIPM Metrologia 20 1 25) not found.
[relaton] (BIPM Metrologia 25 2 113) not found.
[relaton] (BIPM Metrologia 26 1 69) not found.
[relaton] (BIPM Metrologia 27 1 11) not found.
[relaton] (BIPM Metrologia 29 1 1) not found.
[relaton] (BIPM Metrologia 33 1 81) not found.
[relaton] (BIPM Metrologia 34 3 261) not found.
[relaton] (BIPM Metrologia 37 1 87) not found.
[relaton] (BIPM Metrologia 40 2 103) not found.
[relaton] (BIPM Metrologia 41 1 99) not found.
[relaton] (BIPM Metrologia 44 1 97) not found.
[relaton] (BIPM Metrologia 56 2 022001) not found.
[relaton] (BIPM Metrologia 52 1 155) not found.
[relaton] (BIPM Metrologia 43 1 175) not found.
```

**Comment by ronaldtse** [comment]
If the Metrologia fetch syntax changed, can you please help make a PR to the bipm-si-brochure repository to fix them? Thanks.

**Comment by andrew2net** [comment]
@ronaldtse fixed Metrologia references, but the bipm-data-outcomes has only CGPM meetings now. All other documents were deleted by the commit https://github.com/metanorma/bipm-data-outcomes/commit/a67f57e6472c07cb7cfb2debc5680fa6e12bd2d3

**Comment by ronaldtse** [comment]
This is a critical issue. Either this means the scraping tool is now broken or the site has changed. @webdev778 can you help fix this issue ASAP?

**Comment by andrew2net** [comment]
@ronaldtse even in the previous bipm-data-outcomes commit I can't find the "CIPM Decision 2017-10" https://github.com/metanorma/bipm-data-outcomes/tree/f8497331958522130c22680ead003445eb340673/cipm/meetings-en

**Comment by ronaldtse** [comment]
> fixed Metrologia references

@andrew2net I had to remove `~/.relaton/bipm/index.yaml` for Relaton to recognize the updated data. I think we need some way of doing this automatically, e.g. ETag.

**Comment by ronaldtse** [comment]
> even in the previous bipm-data-outcomes commit I can't find the "CIPM Decision 2017-10"

This is the decision:
https://github.com/metanorma/bipm-data-outcomes/blob/f8497331958522130c22680ead003445eb340673/cipm/meetings-en/meeting-106.yml#L164-L180

**Comment by andrew2net** [comment]
@ronaldtse as per [special pattern](https://github.com/relaton/relaton-bipm#special-case-pattern) shouldn't the `CIPM Decision 2017-10` cited as `BIPM Decision CIPM/106-10 (2017)`?

**Comment by ronaldtse** [comment]
@andrew2net the "special pattern" is only for rendering purposes. For fetching we should support the typical syntax.

Also, we have convinced the BIPM to drop the "special pattern" for English (it now only exists in French).

The official reference guidelines are now here:
* https://metanorma.github.io/bipm-editor-guides/documents/bipm-outcomes-en.html

### French

<img width="786" alt="Screenshot 2023-04-19 at 12 00 27 AM" src="https://user-images.githubusercontent.com/11865/232835494-5ffd7e6e-c231-47ba-9184-4b802684a8ba.png">

### English

<img width="803" alt="Screenshot 2023-04-19 at 12 00 42 AM" src="https://user-images.githubusercontent.com/11865/232835569-4b220c2d-2865-463a-8769-7d0f64d20b91.png">


## Language-independent identifiers

We will need to implement the language-independent identifiers as described in the document, too.

**Comment by andrew2net** [comment]
@ronaldtse typical (not specific) pattern is allowed for fetching, but the document number isn't `10`, it's `106-10`. We should put a year in braces `CIPM Decision 106-10 (2017)` for such numbers. The `YYYY-NN` pattern works only for 2 digits document numbers or documents without numbers `CGPM Resolution 1889-00` https://github.com/relaton/relaton-bipm/blob/main/README.adoc#basic-pattern.
The `relaton fetch "CIPM Decision 106-10 (2017)"` works for the [document](https://github.com/metanorma/bipm-data-outcomes/blob/f8497331958522130c22680ead003445eb340673/cipm/meetings-en/meeting-106.yml#L164-L180). Isn't it correct?

**Comment by ronaldtse** [comment]
Yes you're right, it is indeed correct! I've fixed the document. All references are working now.

https://github.com/metanorma/bipm-si-brochure/pull/213
