### ISSUE TITLE
(URGENT) Conflict in document type with Metanorma (`brochure`)

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-bipm#47]
```
[relaton-bib] WARNING: type "brochure" is invalid.
...
Document Attributes: standard is not a legal document type: reverting to 'brochure'
```

The `brochure` document type is a valid type in BIPM.

Issue discovered in:
* https://github.com/metanorma/bipm-si-brochure/pull/213

**Comment by andrew2net** [comment]
@ronaldtse we have `type` and `doctype` attributes. The `type` is defined in the [grammar](https://github.com/relaton/relaton-models/blob/d7115ee43416a2d3bd0b050cda687504282f247e/grammars/biblio.rnc#L265) and can't be `brochure`. The BIPM `doctype` is defined in the [flavor gramma](https://github.com/relaton/relaton-model-bipm/blob/0c5f7ef3582471fdd36322a17d82f1b9f600b229/grammars/relaton-bipm.rnc#L3) and `brochure` is allowed value for it.
The log message said that the `type` attribute has `brochure` value which is invalid.

**Comment by ronaldtse** [comment]
@andrew2net does this mean it is an issue with Metanorma? Ping @opoudjis .

**Comment by andrew2net** [comment]
@ronaldtse If the incorrect type comes from Metanorma then it does.

**Comment by ronaldtse** [comment]
Thank you @andrew2net ! Will wait for @opoudjis to review.

**Comment by opoudjis** [comment]
This is specific to the compilation of collections.

**Comment by opoudjis** [comment]
Suppress error report on default doctype, if no doctype has been supplied at all.
