### ISSUE TITLE
Implement language independent identifiers of BIPM

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-bipm#50]
As described in the BIPM referencing guide:
* https://metanorma.github.io/bipm-editor-guides/documents/bipm-outcomes-en.html

We need to implement language-independent identifiers for BIPM resources.

This supersedes the non-localized element:
```xml
  <docnumber>CIPM -- Recommendation 5 (1989)</docnumber>
```

@andrew2net can you please help go through the document and implement the necessary formats? Thanks!

Related to: https://github.com/metanorma/metanorma-bipm/issues/288

**Comment by andrew2net** [comment]
@ronaldtse we already have 3 identifiers: en, fr, and without language https://github.com/relaton/relaton-data-bipm/blob/5ef306664b14d8eb321d802ade822dab2125cdd2/data/cipm/meeting/recommendation/1989-05.yaml#L37-L50
I don't understand what else we need to implement.

**Comment by andrew2net** [comment]
@ronaldtse I'm trying to understand the BIPM referencing guide. From the bipm-data-outcomes we get meetings, decisions, declarations, recommendations, resolutions, actions. Meetings can have other types.
As I understand we need en, fr, and language-independent IDs:

- meeting - `CIPM 111th meeting (2022)`, `CIPM 111e réunion (2022)`, (I don't find language independent ID description for meetings, do you?)
- decision - `CIPM DECN 111-10 (2022, E)`, `CIPM DECN 111-10 (2022, F)`, `CIPM DECN 111-10 (2022)`
- declaration - `CIPM DECL (1964, E)`, `CIPM DECL (1964, F)`, `CIPM DECL (1964)` (can we omit `resource-specific-id` if we don't have it in the source?)
- recommendation - `CIPM REC 1 (1963, E)`, `CIPM REC 1 (1963, F)`, `CIPM REC 1 (1963)`
- resolution - `CIPM RES 2 (1946, E)`, `CIPM RES 2 (1946, F)`, `CIPM RES 2 (1946)`
- action - there are JCRB actions but I didn't find `resource-type-short` for this type. What should we use for this type?

Are these examples correct?

**Comment by ronaldtse** [comment]
> * meeting - `CIPM 111th meeting (2022)`, `CIPM 111e réunion (2022)`, (I don't find language independent ID description for meetings, do you?)

> * decision - `CIPM DECN 111-10 (2022, E)`, `CIPM DECN 111-10 (2022, F)`, `CIPM DECN 111-10 (2022)`

This is correct.

> * declaration - `CIPM DECL (1964, E)`, `CIPM DECL (1964, F)`, `CIPM DECL (1964)` (can we omit `resource-specific-id` if we don't have it in the source?)

This is correct. Yes, if there is no `resource-specific-id` it means there is only 1 declaration and therefore no number is necessary.

> * recommendation - `CIPM REC 1 (1963, E)`, `CIPM REC 1 (1963, F)`, `CIPM REC 1 (1963)`

This is correct. Similar to the above, if there is no `resource-specific-id` it means there is only 1 so no number is necessary.

> * resolution - `CIPM RES 2 (1946, E)`, `CIPM RES 2 (1946, F)`, `CIPM RES 2 (1946)`

This is correct. Similar to the above, if there is no `resource-specific-id` it means there is only 1 so no number is necessary.

> * action - there are JCRB actions but I didn't find `resource-type-short` for this type. What should we use for this type?

We haven't defined the short format for "JCRB actions" yet. Will consult BIPM.

**Comment by andrew2net** [comment]
fixed in v.1.14.5
